MasterQ32/kristall

Kristall.desktop
See <https://specifications.freedesktop.org/desktop-entry-spec/latest/>.
----
I don't know anything about qmake, so I didn't add the rules.
`Kristall.desktop` has to be installed into `/usr/share/applications/` and
`src/icons/kristall.svg` has to be installed into `/usr/share/pixmaps/` on
Linux.
=> Add Desktop Entry.

README.md, src/certificateselectiondialog.cpp, src/documentstyle.cpp, src/kristall.pro
Assumes a working OpenSSL install at `C:\Program Files\OpenSSL`  
`win32-msvc` encapsulates both 32 and 64 bit msvc builds.
=> Windows (MSVC) build fixes

Makefile
Monitoring the modified state of source files for the build task means
that simply running 'make' will detect if a rebuild is actually needed
or not. Currently if the build file exists make is not run again. A
clean must be run first, then make. This is an improvement on that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/masterq32/kristall/8)
=> adds sourcefiles as dependency to build task

BUILDING.md
- Copying is more robust then the symlink, and I had issues with my system finding the file with a symlink
- Using `update-desktop-database` ensures it will appear in menus, etc
=> Update desktop entry install instructions

BUILDING.md
`qt5-svg` added per this comment: https://aur.archlinux.org/packages/kristall/#comment-753212
Added `-base` to give the `qt` package it's accurate name.
=> Updated info for Arch linux

Makefile
This causes install to create directories in the install path if they do not already exist.
I needed to set `INSTALL="install -D"` while packaging for void as it is installed to an empty directory (See https://github.com/void-linux/void-packages/pull/23336)
=> Pass -D flag to install

src/mainwindow.cpp
Currently if you use ctrl-T (cmd-T on Mac) to open a new tab, you have to manually put focus on the URL bar either with the mouse or ctrl-L. Automatically giving focus to the URL bar when a user opens a new tab is consistent with what they would expect from other graphical browsers (Chrome, Safari, etc.) and allows them to start typing an address right away.
=> Add focus on URL bar when new tab opens

src/browsertab.cpp
This adds "Back" and "Forward" options to the right-click context
menu. This makes it easier to navigate back and forth among pages
without having to navigate the mouse to the upper-left corner
each time.
Signed-off-by: Steve Winslow <steve@swinslow.net>
=> Add back and forward context menu options

src/browsertab.cpp
Fixes a bug where only the background color is styled for error messages, so the error gets the OS text color.
Closes #57
=> Set text color for default stylesheet

src/browsertab.cpp, src/browsertab.hpp, src/protocolhandler.hpp, src/protocols/geminiclient.cpp
I noticed that sensitive input prompt (11) was like normal input (10)
According to specs, it's enough to hide input text
> but the user's input should not be echoed to the screen to prevent it being read by "shoulder surfers"
I choose QLineEdit::Password, but other options are available: QLineEdit::NoEcho and PasswordEchoOnEdit.  Maybe it is something the user want to configure?
=> gemini: respect sensitive input (status 11)

src/mainwindow.cpp
I was tired of moving the mouse just to change tab :)
This is similar to what firefox does (without the 9-> goes to end). Don't know which behaviour is better
=> Switch between tabs with Alt-N

Makefile, src/renderers/markdownrenderer.cpp
Initial support for outline generation in markdown.
It has problems when formatting is applied to headings (like
```markdown
```
would show only hello).  Do you know how to get the full unformatted text?
Thanks
The first commit adds ".PHONY" to the build so that running make after a change will actually rebuild missing parts
=> Markdown Outline generation

ROADMAP.md, src/browsertab.cpp, src/browsertab.hpp, src/mainwindow.cpp, src/mainwindow.hpp, src/mainwindow.ui
The instant theme changing works simply by "flagging" the open tabs for a re-render after the user OKs the settings dialog. This flag is removed when the tab becomes the current tab - it is then re-rendered. 
The current tab (if there is one) is immediately re-rendered and is obviously not flagged afterwards.
I've also added "view page source" to the right-click menu on pages. I guess it seems intuitive to have and was on the roadmap (I assumed it was referring to it being in the right-click menu). I thought I'd might as well include it in this PR since it's such a small addition.
=> Instant theme change

src/browsertab.cpp, src/dialogs/settingsdialog.cpp, src/renderers/geminirenderer.cpp, src/renderers/geminirenderer.hpp
Closes #46, although the real fix for sites was already in #58 – here it is for the rest of the places.
=> Add font color rule for theme previews 

src/mainwindow.cpp, src/mainwindow.ui
Had to use custom properties and rebind the Go home shortcut.
Picked Ctrl+M for opening the Document Outline dock, but I'm not really sure about it.
=> Add shortcuts for quitting Kristall and toggling docks

Kristall.desktop, Makefile, kristall-mime-info.xml, src/main.cpp
As I said in commit logs, this is to run Kristall by double-clicking a file from a file manager and to format it properly.
If you don't like the idea that `QUrl::fromUserInput()` guesses mostly `http://`, then I can change it to something like this instead:
```cc
QUrl url { url_str };
if (url.isRelative()) {
if (QFile::exists(url_str)) {
// url = QUrl::fromLocalFile(url_str) also would work here,
// but the absolute path just looks better for me :^)
url = QUrl::fromLocalFile(QFileInfo(url_str).absoluteFilePath());
} else {
url = QUrl("gemini://" + url_str);
}
}
```
=> Allow to open local files without speciyfing the 'file:' schema from the CLI

src/browsertab.cpp, src/browsertab.hpp, src/mainwindow.cpp, src/mainwindow.hpp, src/renderers/geminirenderer.cpp, src/renderers/geminirenderer.hpp, src/widgets/searchbar.cpp, src/widgets/searchbar.hpp
Page titles are now supported on Gemini and HTML pages, and they are also shown in the window title.
Titles in Gemini documents are extracted in the GeminiRenderer's render function. If the line is a markdown header `#`, the string is copied into a string that is (optionally) passed to the function. This prevents having to re-read the entire document from start to finish just for the title.
The HTML title is extracted from the HTML document's `<title>` tag inside a `<head>` tag. I figured that only searching in the head would be the best option, as [according to this](https://www.w3.org/TR/html4/struct/global.html#edef-TITLE), valid title tags should only appear there. Thus I felt that it'd be less efficient to search past the `<head>` tags. The algorithm I've used to get the title should …
=> New features: page titles, and minor URL bar changes

src/browsertab.cpp
Fixes #80 even though Kristall doesn't actually handle URL fragments currently
Also strips any inline styling from HTML pages, as it can cause conflicts with the user's stylesheet. 
(e.g when visiting https://lukesmith.xyz before this patch, the page background would change colour to yellow, which may make the page unreadable in client's that are using a light font colour)
=> Fix for #80 and strip inline styling in HTML

src/browsertab.cpp, src/browsertab.ui, src/dialogs/settingsdialog.cpp, src/dialogs/settingsdialog.hpp, src/dialogs/settingsdialog.ui, src/kristall.hpp, src/main.cpp, src/mainwindow.ui
The implementation is very simple and can be altered if we end up adding more optional toolbar items
Also adds a setting which stores the user's preference of this.
Also, Ctrl+, is now bound to open the setting dialog - a shortcut you find in many programs
=> Add optional home button to toolbar

src/browsertab.cpp, src/browsertab.hpp, src/dialogs/settingsdialog.cpp, src/dialogs/settingsdialog.hpp, src/dialogs/settingsdialog.ui, src/kristall.hpp, src/main.cpp, src/protocols/filehandler.cpp
* Fixes home toolbar button added in #95. I forgot to include functionality for it yesterday :laughing: 
* ~~file:// protocol now supports reading local text/gemini files (checks for .gmi extension)~~ (not needed)
* Tildes (~) in the URL bar (only under file:// scheme) are now expanded to the user's home directory. Works fine under Linux, but may need testing on Windows. (Example, `file://~` becomes `file://home/user`,`file://~/test` becomes `file:///home/user/test`, and so on)
* Directories in file:// are now displayed as listings of files (screenshot below). Hidden files are optionally enabled via a preference
* URL bar focus cleared after return key press
=> New features - file:// now supports directory listings & text/gemini, +more

src/browsertab.cpp, src/browsertab.hpp, src/documentstyle.cpp, src/mainwindow.cpp, src/mainwindow.hpp, src/protocols/abouthandler.cpp, src/protocols/webclient.cpp, src/renderers/markdownrenderer.cpp
* Fixes a few deprecation warnings and other general warnings
* Fixes a bug in DocumentStyle which caused emojis to not display properly (Fixes #39)
* New feature: mouse buttons 4 and 5 now navigate backward/forward. (Closes #51)
* Slight refactor: MainWindow now has new 'shorthand' methods, curTab, and tabAt, which replace all the `qobject_cast<BrowserTab*>(this->ui->browser_tabs->..)`
* 'Unsupported media type' page is now in gemtext by default. Plaintext version used if user set to use plaintext_only.
* Now strip 'bgcolor' attribute from `<body>` on html pages (continuation of #90). For example when visiting [this page](https://lists.orbitalfox.eu/archives/gemini/2020/date.html) background is no longer changed.
=> Bugfixes, reduce warnings, small refactor

src/browsertab.cpp, src/browsertab.hpp, src/dialogs/settingsdialog.cpp, src/dialogs/settingsdialog.hpp, src/dialogs/settingsdialog.ui, src/kristall.hpp, src/main.cpp, src/mainwindow.cpp, src/mainwindow.hpp, src/widgets/searchbar.cpp, src/widgets/searchbar.hpp
Some subtle formatting is now applied to the URL bar to make the hostname (and port) stand out more in the URL. This is optional and a preference has been added to allow switching to the old URL bar. It's a subtle feature but I think it makes the url bar appear a little nicer
Highlights off:
Highlights on:
The algorithm is quite solid and I haven't come across any urls which it breaks on yet. However, I feel like some of the code might be a little messy (particularly the use of the `settings_visible` variable in the main window class). I'm open to any suggestions for cleaning it up and improvements ;)
=> New url bar formatting

src/browsertab.cpp, src/browsertab.hpp, src/browsertab.ui, src/dialogs/settingsdialog.cpp, src/dialogs/settingsdialog.hpp, src/dialogs/settingsdialog.ui, src/kristall.hpp, src/main.cpp, src/mainwindow.cpp, src/mainwindow.hpp
There are now two options of UI density:
"Compact":
"Classic" (old layout):
I've set 'compact' to be the default. I can change the default setting if you like - I just felt that the 'compact' layout saves some space on the screen and would probably be preferable for new users
=> Add 'compact' layout for UI

src/browsertab.cpp
I couldn't build this on Ubuntu 20.04 (xubuntu) since the last release.  These changes fixed that, but I honestly don't know if this will cause other problems for other QT versions.
Errors I got:
```
$ make
mkdir -p build
cd build;  qmake ../src/kristall.pro && make 
make[1]: Entering directory '/home/gdorn/workspace/kristall/build'
g++ -c -pipe -Wno-unused-parameter -Werror=return-type -std=c++17 -O2 -std=gnu++1z -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DKRISTALL_VERSION="V0.3-136-g0c022e3" -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_MULTIMEDIAWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../src -I. -I../lib/cmark/src -I../lib/luis-l-gist -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtSvg -isystem …
```
=> Fixes for building on ubuntu 20.04 / qt5.12

Kristall.desktop, src/browsertab.cpp, src/browsertab.hpp, src/favouritecollection.cpp, src/favouritecollection.hpp, src/kristall.hpp, src/main.cpp, src/mainwindow.cpp, src/mainwindow.hpp
* slightly changed Kristall.desktop
* Bug fixes and code cleanup for fancy url bar. Now works on pages with URL queries and fragments. Fancy preference setting is now applied instantly, and no longer bugs out after changing UI theme. A custom grey colour is now used for the default Light/Dark themes. 'mid' from palette is still used for OS default theme.
* Favourites: (mostly closes #77) double clicking items in favourites_view now opens page in new tab. No return key press currently though
* Favourites: right click context menu for items now include "Rename" and "Relocate"
* Favourites: page title is now used as favourite name when adding new favourites if such title exists, if not the URL is used as the default title
* Theme: standard icons in OS default theme (#88) are no longer used …
=> Changes to Favourites widget, bugfixes, and other changes

src/browsertab.cpp, src/browsertab.hpp, src/documentstyle.cpp, src/documentstyle.hpp, src/kristall.hpp, src/main.cpp, src/widgets/kristalltextbrowser.cpp, src/widgets/kristalltextbrowser.hpp
* 'busy' cursor is now used while a page is loading on the current tab. (should we make this optional?)
* URL bar highlight colour improved a bit
* Default fonts should be better now. Linux and Mac use a default system font. (**bug**: On Windows I've tried to get it to apply Consolas and Segoe UI by default but it doesn't seem to be using them for some reason. After opening the settings font dialog and pressing accept it does change though)
=> Minor changes

Makefile, src/kristall.pro
`make QMAKE_CONFIG=external-cmark` will try use the external package and will return an error if it couldn't find it.
For this option you must have pkg-config installed (build time dependency).
=> Allow to use external cmark

src/browsertab.cpp, src/browsertab.hpp, src/favouritecollection.cpp, src/favouritecollection.hpp, src/kristall.pro, src/mainwindow.cpp, src/widgets/favouritepopup.cpp, src/widgets/favouritepopup.hpp
There's now also that weird little arrow on the favourite button. It's a bit of a [hassle](https://bugreports.qt.io/browse/QTBUG-2036) to get rid of...
=> New popup when adding to favourites

src/browsertab.ui, src/kristall.pro, src/widgets/favouritebutton.cpp, src/widgets/favouritebutton.hpp
Continues #109 
The width is still a little odd on OS default theme, but it looks perfect in kristall's light/dark themes.
=> Apply favourites button workaround

src/browsertab.cpp, src/browsertab.hpp, src/cachehandler.cpp, src/cachehandler.hpp, src/kristall.hpp, src/kristall.pro, src/main.cpp, src/mainwindow.cpp, src/mainwindow.hpp, src/protocols/abouthandler.cpp, src/widgets/kristalltextbrowser.cpp, src/widgets/kristalltextbrowser.hpp
* Implements a new in-memory caching system. Currently there is no limit - will be added later. Only text documents are cached (HTML _not included_ as these are usually a lot bigger in file size. This can be a preference too in future). Also, if the user has an active client certificate enabled in a tab, caching for that tab is temporarily disabled. This prevents breaking sites like gemini://astrobotany.mozz.us which serves different pages when a user has their certificate attached
* Implements #21 (for cached pages). When navigating to a cached site, the scroll position is remembered and re-loaded.
* Adds a new about:cache page which currently just shows cache usage statistics.
* Fixes two bugs related to the busy cursor added in #108
=> Page caching

src/browsertab.cpp, src/browsertab.hpp, src/cachehandler.cpp, src/cachehandler.hpp, src/favouritecollection.cpp, src/ioutil.cpp, src/ioutil.hpp
* URLs in cache are now saved *without trailing slashes*, so that if a user has e.g `gemini://example.com` in their cache, and they navigate to `gemini://example.com/` (note trailing slash) the page will be read from the cache. This was done using a new method `uniformUrl` in the `IoUtil` class (should we move it somewhere else?)
* Same fix was applied to favourites as they had the same bug.
* Pages now only scroll back to their old scroll pos if the user navigates to them via back/forward buttons or through history. This makes navigating sites less confusing when they click links to pages they've already visited.
=> fixes for cache and favourites

src/browsertab.cpp, src/cachehandler.cpp, src/cachehandler.hpp, src/dialogs/settingsdialog.cpp, src/dialogs/settingsdialog.hpp, src/dialogs/settingsdialog.ui, src/kristall.hpp, src/main.cpp
This implements in-memory caching limits, which can all be adjusted in preferences:
* total cache size
* cached item size threshold (any loaded items above this are not cached)
* cached item life
The 'total cache' works by popping the oldest items in the cache map if adding the current page would exceed the limit. This was a bit of a hack to implement since we are using an unordered_map for the cache map. I feel like the unordered_map works best for just about everything else except this. 
Nevertheless - it works fine :smiley: 
HTML items are now also cached, as the size shouldn't be too much of an issue with the new limits - any massive pages over the configured limit simply would not be cached
=> cache limits

src/browsertab.cpp, src/browsertab.hpp, src/kristall.hpp, src/mainwindow.cpp, src/mainwindow.hpp, src/mimeparser.cpp, src/mimeparser.hpp, src/protocolhandler.hpp, src/protocols/fingerclient.cpp, src/protocols/geminiclient.cpp, src/protocols/gopherclient.cpp, src/protocols/webclient.cpp
* Status bar now displays an indicator that the loaded page is cached. it appears to the left of the page mime type.
* The mime type that is displayed in the status bar now only displays the type/subtype (e.g text/gemini) without any additional parameters, like `lang=...` stuff. I felt like a user wouldn't necessarily need to see that extra stuff
* The status bar now displays some loading information on tabs that are loading (looking up..., connecting..., etc) . This text is in place of where URL previews appear - however URL previews are prioritised over the loading status. (The implementation for HTTP is less informative than the other protocols, as it uses the QNetworkReply which doesn't provide much useful signals)
* Fixes a strange bug where if you navigate to a site (e.g …
=> Status bar updates

src/cachehandler.cpp
Partly reverts commit 50729c19ebf75ab91ee285fe7af86abbdaec411c.
Fixes: #126
=> CacheHandler: don't remove trailing slashes from url

src/browsertab.cpp
The question box was showed when the redirect has a different scheme or host, without checking first if you want to see the it, which could lead to an empty dialog box instead of skipping it entirely.
=> BrowserTab: fix showing an empty redirect question box

src/documentstyle.cpp, src/documentstyle.hpp, src/renderers/renderhelpers.cpp
The only way to set a custom color palette for now is to edit it directly in the config files. I think we shouldn't put them in the settings dialog just yet, as I think it would make settings a bit harder to navigate.
=> Fixes for ANSI escape codes and allow to modify that 16 color palette

src/renderers/gophermaprenderer.cpp
This fixes the icon padding change on Ctrl+Scroll.
=> GophermapRenderer: set default font to the icon format

src/protocols/gopherclient.cpp
Removes 'unhandled network error: QAbstractSocket::RemoteHostClosedError' from logs. Mostly copy-pasted from GeminiClient::socketError. :^)
Closes: #119
=> GopherClient: suppress remote socket closure error

src/dialogs/settingsdialog.cpp, src/dialogs/settingsdialog.hpp, src/dialogs/settingsdialog.ui, src/kristall.hpp, src/main.cpp, src/mainwindow.cpp, src/widgets/browsertabbar.cpp, src/widgets/browsertabbar.hpp, src/widgets/browsertabwidget.cpp, src/widgets/browsertabwidget.hpp
This button is also hidden when the tab-bar is full, as if it were visible it would overlap with the tabs themselves.
=> Added optional 'new tab' button to tab bar

src/mainwindow.cpp
On Firefox, I'm using `Ctrl+PageUp` and `Ctrl+PageDown` all the time to quickly switch between tabs. I was missing this feature on `kristall`, so I thought it would be a neat feature and a good excuse to contribute.
=> Use Ctrl+PageUp/Down to switch between tabs

src/browsertab.cpp
I thought this was a cool feature. An "Open with external browser" option is added to right click menu on HTTP/S links
Closes #53
=> Add 'open in default browser' option on HTTP links

src/browsertab.cpp, src/browsertab.ui, src/kristall.pro, src/widgets/searchbox.cpp, src/widgets/searchbox.hpp
Closes #144
* Return key now moves to next search item
* Shift+Return moves to previous search item
* Searches are wrapped
Had to do this in a new subclass, SearchBox, as setting a QShortcut with Return as the key sequence would cause Return-key usage to be broken elsewhere (e.g in the URL bar). The subclass handles key press events and emits a signal when return/shift+return is pressed.
=> Small search improvements

src/dialogs/settingsdialog.cpp, src/dialogs/settingsdialog.hpp, src/dialogs/settingsdialog.ui, src/documentstyle.cpp, src/documentstyle.hpp, src/renderers/geminirenderer.cpp, src/renderers/textstyleinstance.cpp, src/renderers/textstyleinstance.hpp
This PR makes various changes to help enhance readability of gemtext pages. These changes can be configured through the preferences via new settings added to the Style tab
* Text is now justified by default. Can be toggled
* Line height/spacing is now adjustable for headings and general text.
* Paragraphs, headings, block quotes, and lists now have controllable indent levels. The default configuration indents paragraphs a little bit, and lists a little further. The headings are closest to the left. 
Example page with default values of new options:
=> New gemtext formatting options and improvements

src/dialogs/settingsdialog.cpp, src/dialogs/settingsdialog.hpp, src/dialogs/settingsdialog.ui, src/kristall.hpp, src/main.cpp, src/renderers/geminirenderer.cpp
This replaces double and single quotation marks (", ' respectively) with fancier unicode quotes (‘, ’, “, ”)
It can also be disabled in the preferences (enabled by default)
The implementation works great in all the cases I could think of. For example:
There is however one caveat to this, and that is the **searchbox** feature isn't as intuitive. This is because QTextEdit::find doesn't provide a built-in method of matching the different quote types to each other. This means that if someone was searching for the word "don't" in the searchbox, and had typographer quotes enabled, it would not return any results. This could possibly be fixed in future by using a regex, or some other method.
=> Add support for typographer quotes

src/browsertab.cpp, src/browsertab.hpp, src/dialogs/settingsdialog.cpp, src/dialogs/settingsdialog.hpp, src/dialogs/settingsdialog.ui, src/documentstyle.cpp, src/documentstyle.hpp, src/renderers/geminirenderer.cpp, src/renderers/gophermaprenderer.cpp, src/renderers/markdownrenderer.cpp, src/renderers/plaintextrenderer.cpp, src/renderers/renderhelpers.cpp, src/renderers/renderhelpers.hpp
The main feature of this PR is a new 'maximum text width' option, which helps enhance readability and makes kristall look a lot nicer! This feature should also work with most HTML pages fine
Example with default 900px width:
See 4eefb7d1531fd00f9ae1b185d11ef87a350fc1c2 for implementation details of how this was done
The old layout is still available via a preference.
Additionally, the margins have been split into two preferences now; 'left/right', (horizontal) and 'top/bottom' (vertical). When using maximum text width as shown above, the horizontal margin is used when the window is smaller than the configured text width:
(note the 55px margin between the text and window edge)
Closes #91 
Closes #44
=> Add page text width option, and split margins

src/browsertab.cpp, src/browsertab.hpp
Fixes the issue mentioned in #150 
Search box queries now work for unicode quotation mark types. So e.g: searching for the word `can't` in a page that uses unicode quotation marks will now work correctly. This was achieved by using some regex trickery.
=> Search box improvements: quotation mark matching

src/about/help.gemini, src/browsertab.cpp, src/dialogs/settingsdialog.cpp, src/dialogs/settingsdialog.hpp, src/dialogs/settingsdialog.ui, src/kristall.hpp, src/main.cpp
The URL bar can now perform search queries using a search engine specified in the preferences. This only applies to URL bar entries that appear to not be a URL of any kind.
For example, when the following are entered in the URL bar:
- `gemini.circumlunar.space` -> navigates to `gemini://gemini.circumlunar.space`
- `test` -> performs search query for "test"
- `gemini.circumlunar.space test` -> performs search query (note the space)
- `gemini://test` -> navigates to `gemini://test`
By default the search engine is geminispace.info (happy to change this to something else if wanted). There are 3 search engine options shown to the user in the preferences so that it's easy to switch between common ones.
A section in the help.gemini file was also added for the preference
=> Basic search engine functionality added

src/browsertab.cpp, src/dialogs/settingsdialog.cpp, src/dialogs/settingsdialog.hpp, src/dialogs/settingsdialog.ui, src/documentstyle.cpp, src/documentstyle.hpp, src/renderers/geminirenderer.cpp, src/renderers/markdownrenderer.cpp, src/renderers/textstyleinstance.cpp, src/renderers/textstyleinstance.hpp
* Configurable font and foreground colour for blockquotes
* Blockquotes now work over multiple lines
* Padding inside of blockquotes (currently hard-coded to 16px).
The padding and multi-line stuff was achieved by making blockquotes act as a "table" with a single row and single column, and applying padding etc from there.
Preview:
=> Improved blockquotes

src/browsertab.cpp, src/dialogs/settingsdialog.cpp, src/dialogs/settingsdialog.hpp, src/dialogs/settingsdialog.ui, src/kristall.hpp, src/main.cpp, src/protocols/geminiclient.cpp, src/widgets/kristalltextbrowser.cpp, src/widgets/kristalltextbrowser.hpp
* IBeam cursor is now default. Makes selecting text feel a little more natural
* Tabs that do not have parsable titles in the page now use the document name as the title. Prevents cluttering the tab bar with enormous URLs, etc.
* New 'icon theme' preference: allows the user to override the icon theme if they wish, which is useful for people using the OS Default theme. Also allows users to choose Kristall's light/dark icons instead of the system standard icons if they want. Choices: "Auto", "Light", and "Dark"
=> Some minor changes

src/browsertab.cpp, src/mainwindow.cpp, src/mainwindow.hpp, src/mainwindow.ui
* Simple 'root' and 'parent' navigation options were added to the menu (idea from gemini://mozz.us/journal/2021-01-01.gmi). Currently bound to Alt+/ and Alt+Up respectively right now, but might be changed. 'Root' navigates to the root directory of the current page, 'parent' navigates to the directory above the current. I think we should add these options to the main user interface somewhere as they are very useful, but I'm not sure where or how we should do it.
* Small bug fix: when visiting some sites (one I came across was https://lists.orbitalfox.eu/archives/gemini/2020/000304.html), the tab title would contain a newline character, which made the tab title look strange; newlines are now stripped from tab titles.
* Tab title is now limited to 45 characters. See …
=> Root/parent navigation. Tab title changes

src/about/help.gemini, src/browsertab.cpp, src/browsertab.hpp, src/browsertab.ui, src/cachehandler.cpp, src/dialogs/settingsdialog.cpp, src/dialogs/settingsdialog.hpp, src/dialogs/settingsdialog.ui, src/icons.qrc, src/icons/dark/actions/go-top.svg, src/icons/dark/actions/go-up.svg, src/icons/light/actions/go-top.svg, src/icons/light/actions/go-up.svg, src/kristall.hpp, src/main.cpp, src/mainwindow.cpp, src/mainwindow.ui, src/protocols/fingerclient.cpp, src/protocols/geminiclient.cpp, src/protocols/gopherclient.cpp
* Adds an "unlimited cache item life" option to the settings to disable cache item expiration.
* Applies the fix from #134 for gopher pages to finger pages too, and also fixes the refresh button getting stuck while encountering these errors (socket wasn't being closed).
* Adds new optional 'root' and 'parent' toolbar items. These are disabled by default and were added just to experiment with getting them into the interface. Icons for these have also been created and are used
* Adds some information about many of the new features to the Help document!
=> Various changes (unlimited cache option, a fix, and more)

src/about/help.gemini, src/dialogs/settingsdialog.cpp, src/dialogs/settingsdialog.hpp, src/dialogs/settingsdialog.ui, src/documentstyle.cpp, src/documentstyle.hpp, src/renderers/geminirenderer.cpp, src/renderers/textstyleinstance.cpp
The "experimental text highlights" have now been totally re-written. The implementation is a little ugly and somewhat lengthy, but it seems to work well in all the cases that I tested it in (haven't found any issues/bugs with it yet). I designed the implementation in such a way that should preserve any deliberate usage of the underscore or asterisk in text. So for example if someone where to have a something like_this, or like*this, Kristall would not change it. For kristall to make something bold or underscored, it needs to look something like this:
```
This **will be bold**
This *will be bold*, this will be _underlined_
```
But the following will not be changed:
```
This will not*be*bold
This will not_be_underlined
```
As you can see:
This will also close #141 
Other small changes:
* …
=> Text highlight improvements

src/about/help.gemini, src/dialogs/settingsdialog.cpp, src/dialogs/settingsdialog.hpp, src/dialogs/settingsdialog.ui, src/documentstyle.cpp, src/documentstyle.hpp, src/renderers/geminirenderer.cpp, src/renderers/markdownrenderer.cpp, src/renderers/textstyleinstance.cpp
This adds an option to fine-tune the indentation amounts - which helps when using smaller fonts. By default the indent amount is 15px
Also adds an entry to the Help page, along with documentation of added shortcuts
=> Add 'indent size' option

Makefile
This broke running make with flags like -k or -s set, because make apparently removes hyphens from those flags, making it to think that we want to run a not existing target.
Also, flags are stored in env, so child processes know which flags are in use and we don't have to provide them again.
=> Makefile: remove MAKEFLAGS parameter from sub-make calls

src/dialogs/settingsdialog.cpp
Custom search engines were not being displayed in the combobox after closing/reopening the settings dialog, it was defaulting to the default option. This fixes that.
Also adds the Veronica gopher search engine to list of default options
=> SettingsDialog: search engine combobox fix

src/widgets/kristalltextbrowser.cpp
I was testing kristall on a laptop and noticed that the touch-scrolling feature (since #121) for touch-screen devices also caused devices with touch**pads** to act as if touch scrolling was enabled. 
This causes an annoying bug, where you can click to scroll the page using the mouse, as if the mouse were a finger on a touch screen.
This patch ensures that touch scrolling is only enabled on TouchScreen devices specifically, so the issue no longer occurs with touchpad devices 😉
=> KristallTextBrowser: touch scroll fix

src/kristall.pro
As discussed in #156, appends dpkg-buildflags in qmake. As pointed by @MasterQ32, I tried to not assume that the system has dpkg installed with the `system` function.
It occurred to me now that I'm assuming `which` is installed, but it may not be true on mac and windows (although I think the call to `which` will fail and in consequence the `system` function will just assume a normal failure). So do you think it's necessary to include the `unix { }` declaration (or any other feedback on this PR)?
=> Check if dpkg-buildflags is present and append flags in qmake for hardening purposes

src/documentstyle.cpp, src/documentstyle.hpp, src/main.cpp
This commit should hopefully fix all the font problems we were having. Instead of using font substitution for emojis, we just instead call QFont::setFamilies. Builds with Qt versions below 5.13 will not have proper emoji support - I don't think this should be too much of an issue really
Notable changes:
* emojis seem to work fine at least in my environment
* when selecting a theme (e.g the presets) with font that is not on the system, a respectable default is used instead. 
* Changing fonts from the settings now always works. Previously the fonts would sometimes be "stuck" and changes didn't take affect until re-launching kristall
* a "fallback" font (set to the default font) is added and has higher preference than the emoji fonts, and lower preference than the actual main text font. This …
=> DocumentStyle: potential fixes for font issues

src/about/help.gemini, src/browsertab.cpp, src/dialogs/settingsdialog.cpp, src/dialogs/settingsdialog.hpp, src/dialogs/settingsdialog.ui, src/documentstyle.cpp, src/kristall.hpp, src/main.cpp, src/renderers/geminirenderer.cpp
This adds a preference to disable emojis, as requested in #166 
The preference is greyed out on builds with Qt version lower than 5.13 (i.e emojis unsupported)
Closes #166 
Also small changes: 
* page titles now use original quotation marks from the page (which are usually ASCII quotes) when typographer quotes are enabled. I think this is better as it ensures that the fancy quotes are only a *visual* enhancement to reading the page itself
* parent/root shortcuts now work in error pages and file:// pages
=> Emoji toggle option

src/about/help.gemini, src/dialogs/settingsdialog.cpp, src/dialogs/settingsdialog.hpp, src/dialogs/settingsdialog.ui, src/documentstyle.cpp, src/documentstyle.hpp, src/renderers/geminirenderer.cpp
I thought this is a pretty cool little style feature. The first '#' in the page is centre-aligned. 
It's disabled by default.
=> Add 'centre first H1' option

src/renderers/geminirenderer.cpp
A bit hacky but it seems to work fine without breaking anything else (at least nothing that I've found yet). Maybe someone else has a cleaner idea
Basically if we see a URL on the page that has no hostname, but has same scheme as the root URL, we remove the scheme from it and assume that it is a local URL. (we also have to strip the authority so that leading slashes '//' are removed). The about/file scheme checks might be unnecessary - they're just there to be safe
Closes #181
=> Domain-relative URL fix

.gitignore, Makefile, doc/gem-to-man.awk, doc/gen-man.sh, doc/kristall-head.man, doc/kristall-tail.man, src/about/help.gemini
This PR adds a man page generation script. On Linux man pages are considered the go-to help resource by many, so I feel it's a good idea to create one
Currently, the script looks at the gemtext about:help document, and converts it to the man `roff` format. A 'head' and 'tail' are also added with manpage-specific things (flags, etc) in them.
I've opened this as a draft as there is mostly likely stuff that will have to be changed before actually merging this.
Things to consider:
* Currently, the script strips out the first and last 7 lines of the about:help document which don't really belong in the man page. I think there is a better approach to handling this.
* Not yet added to a make target, so it doesn't get generated automatically yet
* We need to work out where to actually store the …
=> Man page documents

src/main.cpp
Qt translation files were chosen only when you were in /usr/*, because of the relative path.  Changing it to use QLibraryInfo fixes that.
=> main.cpp: use QLibraryInfo to get the exact i18n path

doc/kristall-head.man, src/about/help.gemini
Adds the new `--isolated` and `--new-window` options to the man page. The new window nav menu option is also mentioned in about:help, along with it's shortcut
=> Update help documents

src/renderers/geminirenderer.cpp
* GeminiRenderer code restructured a bit - nesting was reduced a little by removing some unneeded `else`s
* Bolding/underlining now also works in text that is not a paragraph (headings, lists, links, etc. Preformatted text is *not* highlighted)
* Basic ansi escape support for preformatted text in gemtext. No preference as of yet
As shown above, ansi escapes work when used per-lines, however it does not work across multiple lines (e.g the ascii art on gemini://makeworld.space)
=> Gemtext highlighting changes

src/about/help.gemini, src/dialogs/settingsdialog.cpp, src/dialogs/settingsdialog.hpp, src/dialogs/settingsdialog.ui, src/kristall.hpp, src/main.cpp, src/renderers/geminirenderer.cpp, src/renderers/gophermaprenderer.cpp, src/renderers/plaintextrenderer.cpp, src/renderers/renderhelpers.cpp, src/renderers/renderhelpers.hpp
* ANSI Escape sequences now work across multiple lines
* Preferences added to handle this (like mentioned over IRC): "ignore", "interpret (preformatted only)" and "strip"
Still only implemented for preformatted text. I haven't come across any pages which use it outside of preformatted blocks, and I don't know if we should actually allow it outside of them (might mess with the user's theme a little too much?)
=> ANSI escape code stuff

src/mainwindow.cpp, src/mainwindow.ui
Allows navigation of the main QMenuBar via mnemonics (a.k.a accelerators)
I'm not sure how this will affect the localisations thing added in #192 - the translations might need some changes?
Closes #200
=> Add mnemonics to menubar

doc/gen-man.sh
The 'month' in the man page date was set to the 'minute' that the help file was last modified. This resulted in impossible dates like 2021-39-08 :rofl: 
This patch fixes this by using the %F format string when calling `date` in the generation script
=> manpage: fix generated date

src/renderers/geminirenderer.cpp
When viewing gemtext documents that contain CR-LF line endings (such as gemini://idiomdrottning.org/nft), the lines get doubled up, which obviously looks a bit odd.
This patch just strips all CRs from lines in gemtext documents, as there doesn't seem to be any actual reason to have them in there; at least not any reasons I can think of.
=> Strip carriage-returns in gemtext

src/browsertab.hpp, src/kristall.hpp, src/main.cpp, src/mainwindow.cpp, src/mainwindow.hpp
* The last tab being viewed is now restored.
* Tab *titles* are now also saved in the session.ini file alongside their URLs, so that titles are immediately displayed even before loading the pages.
* "Lazyloading" of tabs is added (similar to what web browsers do) - when we restore tabs/windows, only the active tab's page is downloaded. Other tabs are not loaded until the user navigates to that tab
=> Session management: additions

src/browsertab.cpp
Fixes one of the problems from #208
No idea how we should fix the overlapping shortcut problem in the right-click menu
=> Fix minor issue

src/dialogs/settingsdialog.ui
The text is hidden unless the user doesn't have that icon installed.
=> systemdialog.ui: set style buttons names

doc/gem-to-man.awk
on Alpinelinux, for example, awk is at /usr/bin/awk
=> make gem-to-man.awk portable

src/renderers/markdownrenderer.cpp
It caused some spacing issues with nested blockquotes.
Before:
After:
=> MarkdownRenderer: remove resetFormatting function from blockquotes

src/kristall.pro
This initializes QMAKE_CFLAGS, QMAKE_CXXFLAGS and QMAKE_LFLAGS with the
corresponding environment variables on all OSs. The variables will be
expanded when qmake is run[1].
This is a generalization of #171.
[1] <https://doc.qt.io/archives/qt-4.8/qmake-advanced-usage.html#variables>
@charles2910 You'll probably need to update your build script when this PR is merged.
=> Respect *FLAGS environment variables.

src/main.cpp
0d1fd257093c58bfb606aaac530aed3b0877f7fd changed `kristall::saveSettings()` to `settings.sync()` which caused bookmarks not to be saved.
=> Save settings on exit

src/browsertab.cpp
When you viewed a small image after the bigger one in the same tab, then the `graphics_browser` was still trying to scale them to the window size.
=> BrowserTab: reset image scaling for small images

.gitattributes
As you can see in [my private fork](https://github.com/krkk/kristall), github now properly detects the language of this project!
https://github.com/github/linguist/blob/master/docs/overrides.md
[skip ci]
=> .gitattributes: exclude libraries from GitHub language detection

src/browsertab.cpp, src/dialogs/certificatemanagementdialog.cpp, src/dialogs/settingsdialog.cpp, src/mainwindow.cpp, src/protocols/filehandler.cpp
We don't need to wrap tr() with QString, because it returns QString anyway. Although it doesn't change the binary size (mostly because compilers were smart to remove that already), it helps to make the code a little bit cleaner.
It's a somewhat continuation of c740189, but I thought back then it happened only there, so now I've removed it from all places.
=> Unwarp tr() from QStrings

src/main.cpp
Before this change, only the first user who had opened kristall had working ipc.
The easiest fix was to prepend an username to the socket and that's exactly what it does on Windows.
On Linux and other UNIX systems, we could do that too, but I came up with a bit different approach. I didn't like the fact that Qt puts sockets in /tmp, but luckily we can provide the full path for the socket (Windows uses pipes, so that's why it has its own case). I've changed it to put sockets in the runtime directory, because it's designed for that type of files and it's user-specific, so we don't even have to prepend the username to it.
---
I couldn't test that on Windows but I have crossed fingers it works as intended.
=> main.cpp: support sessions when multiple users have opened Kristall

src/browsertab.cpp, src/mainwindow.cpp
When lazy-loaded links were making a new tab, they wasn't calling `tab->navigateTo(url, BrowserTab::PushImmediate)`. What's important is only it can push urls to the history and making a new function just for that seemed like it'd just complicate things.
So I've changed it to call `tab->navigateTo()` on every loading type. Unfortunately, that fixed our issue partly. Sure, links are now put into the history, but lazy-loaded tabs stopped being lazy-loaded anymore. Moreover, they were also reloading a page on first tab switch.
So I've made also a check that stops requesting lazy-loaded urls, which made lazy-loading work as intended again, and moved the unsetting lazy-loaded boolean on reload instead of right after it to be able to request the file, which finally...
Closes: #214
=> Push lazy-loaded links to the history

Makefile, src/kristall.pro
Homebrew installs to a different directory on macOS/arm64.
this adds checks in the Makefile and in kristall.pro, and sets
the correct paths to Homebrew depending on whether the build is
targeting arm64 or not.
=> Fix building on macOS/arm64

doc/gen-man.sh
the + and - syntax on head and tail are only present, as far as i know,
in GNU coreutils, and are not present on any other UNIX or BSD systems.
this patch replaces those with a more portable processing chain, which
is tested to work on GNU coreutils, NetBSD, macOS, and busybox.
=> doc/gen-man.sh: head and tail +/- syntax is not portable

.gitignore, doc/gen-man.sh
usage of the "-i" feature of sed is not entirely portable across
different operating systems. -i has an optional extension to save
a backup of the edited file, and different systems parse this option
in a different manner.
the sed in GNU, busybox, NetBSD, and OpenBSD expects the argument
to be immediately after, like `-i.bak`, if it is present.
the sed in macOS and FreeBSD expects the argument to follow after
a space, like `-i .bak`, but will accept the `-i.bak` form as well.
the issue is that when no backup is specified, the first requires
just `-i`, where the second requires `-i ''`. the easiest way around
this is to just add a backup, which is what i chose to do here. i
also added the .bak extension to the .gitignore.
additionally, all aforementioned seds except for GNU usually require …
=> doc/gen-man.sh: make sed command portable

BUILDING.md, Makefile, src/kristall.pro
It is a very small difference, qt5 instead of qt in some paths. Maybe I am wrong about this being necessary to merge, but builds properly for me if I make these changes vs no changes.
=> Fix macos build for m1 - macos 11 & current homebrew

BUILDING.md
By default, after installing qt, users won't have qmake in their path. An additional command is needed to do this.
=> Add additional brew command for macOS building

doc/kristall-head.man, src/kristall.pro
Hi, as mentioned in #244, 83c9cc5a6b65952f1ef0534b87e8fc62a51b2f05 fixes the build reproducibility problem and e1311b8f393a33c16aa9310f3354157e6da48141 fixes the build flags problem.
Appending the CPPFLAGS to CFLAGS and CXXFLAGS builds fine in debian and debian derivatives. Since 7074170f69fdf8b4d41954ab42d48fea971293b3 the flags are expanded for all OSs by qmake, so I don't think it'll be a problem. Though I don't have windows or mac machines to try it out (if someone has and could check, it'd be awesome).
=> Apply Debian patches

BUILDING.md, src/about/help.gemini
Hi, the 3 commits do the following:
- ace7c440644655a74d4caf45ea05e2d3d468448c fixes a typo in `help.gemini`;
- 101ad24c91f8131b3d348eda214486851c7951d2 adds info about Debian;
- 6306b51ee09fc3da4d59d1ed0b2850b30a9276c9 fixes #262 by adding a required package in Arch.
=> Fix typo and update building documentation

src/widgets/mediaplayer.cpp, src/widgets/mediaplayer.hpp
Only call setPosition() on the QMediaPlayer object when the user has manually dragged the slider position slider.
Otherwise the slider and player will call each other, probably causing a feedback loop which causes stuttering.
=> Fix media player stuttering

src/browsertab.cpp
This only seems to happen in the GopherClient. It's easiest to reproduce the crash when downloading a large file, and closing the tab before the download has completed.
I think this happens because when the BrowserTab is closed it deletes the client, but the client has still got it's signals connected. So when the GopherClient [emits 'requestProgress'](https://github.com/entropic77/kristall/blob/fix-crash-on-close-tab/src/protocols/gopherclient.cpp#L115), the deleted BrowserTab's `on_requestProgress` will be called, where it calls [kristall::globals()](https://github.com/entropic77/kristall/blob/fix-crash-on-close-tab/src/browsertab.cpp#L1268), which seems to cause the crash.
Fixed by calling `this->current_handler->cancelRequest();` in the [BrowserTab …
=> Fix crash when closing gopher tab during content loading

src/renderers/renderhelpers.cpp
Add bounds checking before increasing iterator pointer, to prevent incomplete ANSI codes causing iterators going to far.
=> Fix crash when encountering incomplete ANSI codes

src/widgets/kristalltextbrowser.cpp
If text is selected, middle-click will not be forwarded to the function that opens the link in a new tab. So this change will deselect any selected text before trying to open a new tab.
Fixes #253
=> Allow middle-click to open new tab when text is selected

src/browsertab.cpp
This change allows the user to start scrolling with the keyboard instantly, without having to focus the browsing area first, after a page has loaded.
This happens for example when opening a new tab, and when entering an address manually.
=> Focus browsing area after page is loaded

doc/gen-man.sh
3a015f7 fix a escape char problem in sh (#274)  and 710a5fc remove unused logic from gen-man script.
=> Fix manpage generation in sh shell and gen-man.sh cleanup

doc/gen-man.sh
Hi again, Felix.
So, I should have researched a little bit more before proposing the fix :-) Turns out we can use `printf` to have a more predictable behavior printing things. With this change, using bash or sh generates the same output!
=> Build manpage reproducible 

src/dialogs/settingsdialog.cpp
Fixes #279 By adding Kennedy and TLGS as search engines, removing GUS and Houston which no longer exist
=> Fixes #279: Updates dialog with active search engines

src/renderers/gophermaprenderer.cpp
Paths in Gophermaps that start with “URL:” should be interpreted as direct URLs, rather than references to files or directories on the Gopher server itself.
An excerpt from the document describing this feature/standard:
```
Links to URLs from a gopher directory shall be defined as follows:
Type -- the appropriate character corresponding to the type of the
document on the remote end; h if HTML.
Path -- the full URL, preceeded by "URL:".  For instance:
URL:http://www.complete.org/
Host, Port -- pointing back to the gopher server that provided
the directory for compatibility reasons.
Name -- as usual for a Gopher directory entry.
```
Source: gopher://quux.org/0/Archives/Mailing Lists/gopher/gopher.2002-02?/MBOX-MESSAGE/34
An example of this in the wild can be seen at …
=> Support URLs in Gophermaps

src/browsertab.cpp
Some Gemini sites such as Station or BBS allow multi-line posts.
=> browsertab.cpp: Use multi-line input when required

src/dialogs/settingsdialog.ui
This would allow smaller screens (think of mobile devices such as the PinePhone or Librem 5) to be able to fit the settings dialog, and therefore use it.
=> settingsdialog.ui: Move "Generic" widgets to QScrollArea

CMakeLists.txt, src/browsertab.cpp, src/kristall.pro, src/widgets/querydialog.cpp, src/widgets/querydialog.hpp, src/widgets/querydialog.ui
Recent commits allowed multi-line input while reusing the `QInputDialog` object already defined by Kristall. However, `QInputDialog` lacks a way to access its `QPlainTextEdit` directly, and therefore set the wrap mode.
Since `QInputDialog` does no wrapping, it is inconvenient for writing a long text (think of social media sites such as [BBS](gemini://bbs.geminispace.org) or [Station](gemini://station.martinrue.com)). Therefore, a custom `QDialog`-derived class, namely `QueryDialog`, has been provided.
If data is sensitive (e.g.: passwords), `QueryDialog` hides its `QPlainTextEdit` and shows a `QLineEdit`, and vice versa.
=> Replace `QInputDialog` with custom dialog for queries

CMakeLists.txt, src/browsertab.cpp, src/dialogs/settingsdialog.ui, src/kristall.pro, src/protocols/guppyclient.cpp, src/protocols/guppyclient.hpp, src/protocolsetup.hpp
Protocol is described in gemini://gemini.dimakrasner.com/guppy-v0.4.gmi (or guppy://gemini.dimakrasner.com/guppy-v0.4.gmi).
It would be super nice to have it supported in Kristall, because without great clients there won't be great servers.
=> Add guppy:// v0.4 support

src/widgets/querydialog.ui
As the query label is determined by the remote server, it can be arbitrarily long. Therefore, it makes sense to enable word wrap so the dialog still fits on devices with smaller screens, such as mobile phones.
=> `querydialog.ui`: Allow smaller dialog size
