BUILDING.md, README.md
=> Update instructions to build on macOS

src/renderers/markdownrenderer.cpp
Hi! In the process of adding kristall to guix, Christopher Baines noticed that some libraries are "bundled" (source is included in the repo).  In guix we usually try to unbundle as much as possible (and use the software for which we already have a package).
In the process of unbundling cmark (more details [here](https://issues.guix.gnu.org/44191)), I saw that you are including node.h and using details of the cmark_node struct.  I replaced those with functions exported in the cmark.h header.
I never used cmark before, so I'm not sure my changes are correct.  Also I could not find tests, so the only thing I did was to open a markdown link and see if it was rendered correctly.
More tests are probably required
=> markdown renderer: use only exported cmark functions

BUILDING.md
When building kristall, I discovered three additional required packages.
=> Add additional required packages for Fedora 32+

src/browsertab.cpp, src/renderers/markdownrenderer.cpp, src/renderers/markdownrenderer.hpp
=> Escape HTML sequences in title and add Markdown title parsing

src/renderers/markdownrenderer.cpp
This function is getting to much arguments..
=> MarkdownRenderer: indent lists

src/favouritecollection.cpp, src/trustedhostcollection.cpp
Not sure if it is the right way though.
Fixes: #112
=> {TrustedHost,Favourite}Collection: fix duplicating/removing the last item

src/browsertab.cpp, src/favouritecollection.cpp, src/favouritecollection.hpp, src/mainwindow.cpp, src/mainwindow.hpp, src/mainwindow.ui, src/widgets/favouritepopup.cpp, src/widgets/favouritepopup.hpp
=> Added group to favourites popup

src/widgets/kristalltextbrowser.cpp
As requested by 'paper' on IRC :wink: 
Not sure how this will behave on other touchscreen devices though.
=> Touch scroll support

presets/DOS.kthm
you need `PxPlus IBM VGA 9` font from [The Oldschool PC Font Resource](https://int10h.org/oldschool-pc-fonts/download/)
=> DOS color scheme

BUILDING.md
Please comment if these changed were not needed on your system, as they were needed on mine.
=> Updated BUILDING.md to include aditional instuctions required for building on FreeBSD

src/protocols/gopherclient.cpp
Kinda hacky, but uhhh it works  ¯\\_(ツ)_/¯
Closes: #165
=> GopherClient: add text-search support

src/dialogs/settingsdialog.cpp, src/dialogs/settingsdialog.ui
=> SettingsDialog: make style settings scrollable

src/renderers/geminirenderer.cpp
=> GeminiRenderer: list indentation fix

src/renderers/renderhelpers.cpp
=> Fix double line-feed in plain text documents

src/browsertab.cpp, src/dialogs/certificateiodialog.cpp, src/dialogs/certificatemanagementdialog.cpp, src/dialogs/settingsdialog.cpp, src/ioutil.cpp, src/kristall.pro, src/kristall_en_US.ts, src/main.cpp, src/mainwindow.cpp, src/protocols/abouthandler.cpp, src/trustedhostcollection.cpp, src/widgets/favouritepopup.cpp, translations/kristall_en_US.ts, translations/kristall_ru.ts
Changes necessary for implementing interface translation. (Closes !191)
Russian translation of kristall.
=> Basic support for localization

src/browsertab.hpp, src/dialogs/settingsdialog.cpp, src/dialogs/settingsdialog.hpp, src/dialogs/settingsdialog.ui, src/kristall.hpp, src/main.cpp, src/mainwindow.cpp, src/mainwindow.hpp
Implements #187
@mikejzx can you take a look at it before merging?
=> Session management

doc/gen-man.sh, src/icons/mac-icon.sh, src/icons/update-themes.sh
=> don't depend on bash

src/widgets/ssltrusteditor.cpp, src/widgets/ssltrusteditor.ui
=> ssltrusteditor: fix incorrect index on revocation

BUILDING.md, src/kristall.pro
Fixes OOM error on font qcg for x86  32 systems where memory is low or g++ cant handle allocating more than 4GB
=> Fix x86 for Haiku and maybe others

src/browsertab.cpp, src/kristall.pro, src/protocols/abouthandler.cpp, src/renderers/renderhelpers.cpp, src/widgets/kristalltextbrowser.cpp, src/widgets/mediaplayer.cpp, src/widgets/mediaplayer.hpp
With QT_VERSION_CHECK and core5compat module
AboutHandler: improve cache request generation
Specify Utf8 encoding for cache information header
=> Introduce Qt 6 support

src/widgets/mediaplayer.cpp
Add missing mediaplayer widget logic
Contributes to:
https://github.com/MasterQ32/kristall/pull/266
=> Improve Qt 6 support

README.md
Closes https://github.com/MasterQ32/kristall/issues/291
=> Add information for bundled dependencies

Kristall.metainfo.xml, Makefile
Closes https://github.com/MasterQ32/kristall/issues/293
=> Add app data file

CMakeLists.txt
Closes https://github.com/MasterQ32/kristall/issues/295
=> Enable installation using CMake
